### ISSUE TITLE
Whois module ipaddr exceptions 

### ISSUE THREAD

**Issue by deadbits** [InQuest/omnibus#28]
IPWhois module apparently requires ipaddr but doesn't install it in some cases and this exception was reported by a user. Need to investigate, potentially switch to different package version or method of getting whois info

omnibus >> whois 1.1.1.1

[!] Failed to load module (whois)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 1653, in onecmd_plus_hooks
stop = self.onecmd(statement)
File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 1848, in onecmd
stop = func(statement)
File "omnibus-cli.py", line 634, in do_whois
result = self.dispatch.submit(self.session, 'whois', arg)
File "/root/omnibus/lib/dispatch.py", line 131, in submit
result = self.run(module, artifact)
File "/root/omnibus/lib/dispatch.py", line 167, in run
raise err
ImportError: No module named ipaddr
EXCEPTION of type 'ImportError' occurred with message: 'No module named ipaddr'

after running pip install ipaddr it gives the following:

omnibus >> whois 115.23.21.1
/usr/local/lib/python2.7/dist-packages/ipwhois/nir.py:443: UserWarning: NIRWhois._get_nets_krnic() has been deprecated and will be removed. You should now use NIRWhois.get_nets_krnic().
warn('NIRWhois._get_nets_krnic() has been deprecated and will be '
[!] Caught unhandled exception: 'str' object does not support item assignment
{
"asn": "4766"
}

**Comment by deadbits** [comment]
Above issue brought to light by @grispan56

**Comment by davisjackie321** [comment]
Tt

**Comment by davisjackie321** [comment]
Jki
